services:
  gui-app:
    build: .
    container_name: virtual-gui-server
    privileged: true
    ports:
      - "5900:5900"
    shm_size: '2gb'
    environment:
      - DOMAIN_NAME=p.webshare.io
      - PROXY_PORT=80
      - PROXY_USERNAME=pnfglwjv-BR-rotate
      - PROXY_PASSWORD=8q805viq23l5
